%% Setup the Report (PDF and DOCX)
import mlreportgen.report.*
import mlreportgen.dom.*

% Define output report names
pdfReportName = 'FinalDocumentationReport.pdf';
docxReportName = 'FinalDocumentationReport.docx';

% Create Report objects
pdfRpt = Report('FinalDocumentationReport','pdf');
docxRpt = Report('FinalDocumentationReport','docx');

% Common setup for both reports
for rpt = [pdfRpt, docxRpt]
    rpt.Layout.Landscape = false; % Set report orientation
    rpt.TitlePage.Title = 'Project Code Documentation Report';
    rpt.TitlePage.Subtitle = 'Generated by MATLAB Report Generator';
    rpt.TitlePage.Author = 'Your Name';
end

% This function adds the main content to a given report
function buildReportContent(rpt)
    import mlreportgen.report.*
    import mlreportgen.dom.*

    open(rpt);

    % Add a table of contents
    toc = TableOfContents;
    add(rpt,toc);

    % Find all the improved code files (report_*.m)
    files = dir('report_*.m');
    if isempty(files)
        warning('No report_*.m files found in the current directory.');
    end

    %% Iterate Over Each File
    for i = 1:length(files)
        filename = files(i).name;

        % Create a chapter for each file
        ch = Chapter();
        ch.Title = strrep(filename,'_','\_'); % Escape underscores in titles

        % Add a brief introduction about the file
        p = Paragraph(['This section documents the code found in ', filename, '.']);
        p.Style = {Color('Black'),FontSize('12pt')};
        add(ch,p);

        % Insert the code as a listing using CodeExtraction and Code
        codeSection = Section('Documented Code');
        codeObj = CodeExtraction(filename);
        codeBlock = Code(codeObj);
        add(codeSection, codeBlock);
        add(ch, codeSection);

        % Optional: Execute the code and capture output or figures
        % If you want to show figures generated by the code:
        %{
        run(filename);
        figHandles = findall(0,'Type','figure');
        for f = figHandles'
            % Save figure to a temporary image file
            imgName = [tempname,'.png'];
            exportgraphics(f,imgName,'Resolution',150);
            figPara = Paragraph('Figure generated by the code:');
            figPara.Style = {Color('Black'),FontSize('10pt')};
            add(ch,figPara);

            img = Image(imgName);
            img.Style = {ScaleToFit};  
            add(ch,img);

            close(f); % close figure after capturing
        end
        %}

        % Add the chapter to the report
        add(rpt,ch);
    end

    close(rpt);
end

% Build content for both reports
buildReportContent(pdfRpt);
buildReportContent(docxRpt);

% View the PDF report (if supported on your system)
rptview(pdfRpt);

% The DOCX report is now in DOCX format and can be tweaked with a word processor
% After editing, you can export it to PDF from your word processor or run:
% publish the docx to pdf using external tools if needed.
